# PostgreSQL configuration:
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = user
quarkus.datasource.password = pass
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/order_system_db

quarkus.hibernate-orm.schema-management.strategy=update
# quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=false

# CONFIGURACIÓN DE REDIS
quarkus.redis.hosts=redis://localhost:6379

# ==========================================
# CONFIGURACIÓN DE KAFKA (JACKSON OFICIAL)
# ==========================================
kafka.bootstrap.servers=localhost:9092
quarkus.kafka.devservices.enabled=false

# PRODUCER
mp.messaging.outgoing.ordenes-out.connector=smallrye-kafka
mp.messaging.outgoing.ordenes-out.topic=ordenes
mp.messaging.outgoing.ordenes-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# mp.messaging.outgoing.ordenes-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# CONSUMER
mp.messaging.incoming.ordenes-in.connector=smallrye-kafka
mp.messaging.incoming.ordenes-in.topic=ordenes
mp.messaging.incoming.ordenes-in.value.deserializer=order.event.OrderCreatedEventDeserializer
# mp.messaging.incoming.ordenes-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.incoming.ordenes-in.auto.offset.reset=earliest

# quarkus.log.category."io.smallrye.reactive.messaging.kafka".level=DEBUG
# quarkus.log.category."org.apache.kafka.clients.consumer".level=DEBUG

# Asegura que el broker confirme la escritura en disco antes de dar el envío por bueeno
mp.messaging.outgoing.ordenes-out.acks=all

# Si hay un amago de desconexión, que intente reenviar automáticamente
mp.messaging.outgoing.ordenes-out.retries=3

