# PostgreSQL configuration:
quarkus.datasource.db-kind = ${DB_KIND:postgresql}
quarkus.datasource.username = ${DB_USER:user}
quarkus.datasource.password = ${DB_PASS:pass}
quarkus.datasource.jdbc.url = jdbc:${DB_KIND:postgresql}://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:order_system_db}

quarkus.hibernate-orm.schema-management.strategy=update
# quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=false

# CONFIGURACIÓN DE REDIS
quarkus.redis.hosts=redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}

# ==========================================
# CONFIGURACIÓN DE KAFKA (JACKSON OFICIAL)
# ==========================================
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
quarkus.kafka.devservices.enabled=false
# Permite que Quarkus le pida a Kafka crear tópicos en tiempo de ejecución si no existen
kafka.auto.create.topics.enable=true
# Fuerza a Kafka a guardar de forma automática que ya leyó y procesó el mensaje
mp.messaging.incoming.order-created-in.enable.auto.commit=true

# ------------------------------------------
# PRODUCERS (OrderProducer)
# ------------------------------------------
# Canal: order-created-out -> Tópico: order-created
mp.messaging.outgoing.order-created-out.connector=smallrye-kafka
mp.messaging.outgoing.order-created-out.topic=order-created
mp.messaging.outgoing.order-created-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.order-created-out.acks=all
mp.messaging.outgoing.order-created-out.retries=3

# Canal: order-verified-out -> Tópico: order-verified (El que escuchará n8n)
mp.messaging.outgoing.order-verified-out.connector=smallrye-kafka
mp.messaging.outgoing.order-verified-out.topic=order-verified
mp.messaging.outgoing.order-verified-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.order-verified-out.acks=all
mp.messaging.outgoing.order-verified-out.retries=3

# ------------------------------------------
# CONSUMERS (OrderCreatedConsumer)
# ------------------------------------------
# Canal: order-created-in <- Tópico: order-created
mp.messaging.incoming.order-created-in.connector=smallrye-kafka
mp.messaging.incoming.order-created-in.topic=order-created
mp.messaging.incoming.order-created-in.value.deserializer=order.kafka.OrderEventDeserializer
# Le indicamos a Jackson a qué clase mapear el JSON entrante
mp.messaging.incoming.order-created-in.target-class=order.dto.OrderEvent
mp.messaging.incoming.order-created-in.auto.offset.reset=earliest

# quarkus.log.category."io.smallrye.reactive.messaging.kafka".level=DEBUG
# quarkus.log.category."org.apache.kafka.clients.consumer".level=DEBUG

